INSERT INTO wavefire.NOTIFICATION_END_POINT (END_POINT_ID, END_POINT_NAME) VALUES((SELECT COALESCE(MAX(END_POINT_ID)+1, 1) FROM wavefire.NOTIFICATION_END_POINT), 'Student');
INSERT INTO wavefire.NOTIFICATION_END_POINT (END_POINT_ID, END_POINT_NAME) VALUES((SELECT COALESCE(MAX(END_POINT_ID)+1, 1) FROM wavefire.NOTIFICATION_END_POINT), 'Employee');
INSERT INTO wavefire.NOTIFICATION_END_POINT (END_POINT_ID, END_POINT_NAME) VALUES((SELECT COALESCE(MAX(END_POINT_ID)+1, 1) FROM wavefire.NOTIFICATION_END_POINT), 'Notice Board');

INSERT INTO wavefire.NOTIFICATION_MODE (MODE_ID, MODE_NAME) VALUES((SELECT COALESCE(MAX(MODE_ID)+1, 1) FROM wavefire.NOTIFICATION_MODE), 'EMAIL');
INSERT INTO wavefire.NOTIFICATION_MODE (MODE_ID, MODE_NAME) VALUES((SELECT COALESCE(MAX(MODE_ID)+1, 1) FROM wavefire.NOTIFICATION_MODE), 'SMS');

INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Registration'); 
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Monthly Attendance Report');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Yearly Attendance Report');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Exam Result');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Leave Notification');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Fee Summary');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Birthday Greeting');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Payslip');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Service Letter');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Promotion Letter');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Declare Holiday(s)');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'Achievements');
INSERT INTO wavefire.NOTIFICATION_TYPE (TYPE_ID, TYPE_NAME) VALUES((SELECT COALESCE(MAX(TYPE_ID)+1, 1) FROM wavefire.NOTIFICATION_TYPE), 'General Notice');

-- student email templates
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Registration'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Monthly Attendance Report'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Yearly Attendance Report'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Exam Result'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Leave Notification'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Fee Summary'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Birthday Greeting'));
-- student SMS templates
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Registration'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Monthly Attendance Report'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Yearly Attendance Report'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Exam Result'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Leave Notification'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Fee Summary'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 1, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Birthday Greeting'));

-- employee email templates
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Registration'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Monthly Attendance Report'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Yearly Attendance Report'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Leave Notification'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Birthday Greeting'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Payslip'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Service Letter'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Promotion Letter'));
-- employee SMS templates
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Registration'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Monthly Attendance Report'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Yearly Attendance Report'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Leave Notification'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Birthday Greeting'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Payslip'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Service Letter'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 2, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Promotion Letter'));

-- Notice Board email templates
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 3, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Declare Holiday(s)'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 3, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Achievements'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 3, 1, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='General Notice'));
-- Notice board SMS templates
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 3, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Declare Holiday(s)'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 3, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='Achievements'));
INSERT INTO wavefire.NOTIFICATION_TEMPLATE (TEMPLATE_ID, END_POINT_ID, MODE_ID, TYPE_ID) VALUES(
    (SELECT COALESCE(MAX(TEMPLATE_ID)+1, 1) FROM wavefire.NOTIFICATION_TEMPLATE), 3, 2, (SELECT TYPE_ID FROM wavefire.NOTIFICATION_TYPE WHERE TYPE_NAME='General Notice'));

INSERT INTO wavefire.NOTIFICATION_STATUS (STATUS_CODE, DESCRIPTION) VALUES(
    'NEW', 'This notification has been requested in the recent past. This notification has never undergone processing.');
INSERT INTO wavefire.NOTIFICATION_STATUS (STATUS_CODE, DESCRIPTION) VALUES(
    'PARTIAL', 'This notification has been partially processed. This notification will be processed again (Only those detail records which have not been process yet).');
INSERT INTO wavefire.NOTIFICATION_STATUS (STATUS_CODE, DESCRIPTION) VALUES(
    'DELIVERED', 'This notification has been delivered successfully and completely.');
INSERT INTO wavefire.NOTIFICATION_STATUS (STATUS_CODE, DESCRIPTION) VALUES(
    'UNDELIVERED', 'This notification may be processed partially but failed to deliver. This notification is given up because of failures.');
INSERT INTO wavefire.NOTIFICATION_STATUS (STATUS_CODE, DESCRIPTION) VALUES(
    'ABONDENED', 'This notification may be processed partially but cancelled by the user.');
