INSERT INTO wavefire.ORGANIZATION (ID, NAME, ADDRESS, PHONE_NUMBER, FAX_NUMBER)
  VALUES (1, 'My Organization', 'L-108, 25th Cross, Sankranthi Circle, Mysore', '1234567890', '1234567890');


INSERT INTO wavefire.ORGANIZATION_PREFERENCES (ORGANIZATION_ID,
    NOTIF_USE_EMAILS, NOTIF_EMAIL_EMPLOYEES, NOTIF_EMAIL_STUDENTS,
    NOTIF_USE_TEXT, NOTIF_TEXT_EMPLOYEES, NOTIF_TEXT_STUDENTS,
    USE_MENU_ICONS, DEFAULT_THEME, PINNED_GALLERY,
    USE_EMPLOYEE_SELF_SUBMIT, USE_STUDENT_SELF_SUBMIT)
  VALUES (1, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'SECRET_KEY', NULL, 'Y', 'Y');


INSERT INTO wavefire.ORGANIZATION_MANIFEST(ORGANIZATION_ID, CURRENT_AY_NAME, MAP_URL, AYE_IN_PROGRESS)
  VALUES(1, (select ACADEMIC_YEAR_NAME from ACADEMICS order by AY_START_DATE desc LIMIT 1), NULL, 'N');

