CREATE TABLE REF_RELATIONSHIP (
    CODE char(1) NOT NULL,
    NAME varchar(32) NOT NULL,
    PRIMARY KEY (CODE)
);
ALTER TABLE REF_RELATIONSHIP ADD UNIQUE (CODE);
ALTER TABLE REF_RELATIONSHIP ADD UNIQUE (NAME);


CREATE TABLE REF_CREDIT_TYPE (
    CODE char(1) NOT NULL,
    DESCRIPTION varchar(32) NOT NULL,
    PRIMARY KEY (CODE)
);
ALTER TABLE REF_CREDIT_TYPE ADD UNIQUE (CODE);
ALTER TABLE REF_CREDIT_TYPE ADD UNIQUE (DESCRIPTION);

CREATE TABLE DOCUMENT (
    DOCUMENT_ID integer NOT NULL,
    DOCUMENT_NAME varchar(64) NOT NULL,
    DESCRIPTION varchar(512) NOT NULL,
    STUDENT_APPLICABLE char(1) NOT NULL DEFAULT 'N',
    EMPLOYEE_APPLICABLE char(1) NOT NULL DEFAULT 'N',
    PRIMARY KEY (DOCUMENT_ID)
);
ALTER TABLE DOCUMENT ADD UNIQUE (DOCUMENT_ID);
ALTER TABLE DOCUMENT ADD UNIQUE (DOCUMENT_NAME);


CREATE TABLE REF_MODULE (
    MODULE_ID smallint NOT NULL,
    MODULE_NAME varchar(32) NOT NULL,
    CAN_ADMIN_ACCESS varchar(1) NOT NULL,
    CAN_EMPLOYEE_ACCESS varchar(1) NOT NULL,
    CAN_STUDENT_ACCESS varchar(1) NOT NULL,
    ACCESS_URL varchar(64) NULL,
    PRIMARY KEY (MODULE_ID)
);

ALTER TABLE REF_MODULE ADD UNIQUE (MODULE_ID);
ALTER TABLE REF_MODULE ADD UNIQUE (MODULE_NAME);


CREATE TABLE FUNCTION (
    FUNCTION_ID bigint NOT NULL,
    FUNCTION_NAME varchar(32) NOT NULL,
    REF_MODULE_ID smallint NOT NULL,
    ACCESS_URL varchar(64) NULL,
    ICON_URL varchar(64) NULL,
    PRIMARY KEY (FUNCTION_ID)
);
ALTER TABLE FUNCTION ADD UNIQUE (FUNCTION_ID);
ALTER TABLE FUNCTION ADD CONSTRAINT FK_REF_MODULE_ID FOREIGN KEY (REF_MODULE_ID) REFERENCES REF_MODULE (MODULE_ID);
