CREATE TABLE REF_STATE (
    STATE_ID smallint NOT NULL,
    STATE_NAME varchar(32) NOT NULL,
    PRIMARY KEY (STATE_ID)
);
ALTER TABLE REF_STATE ADD UNIQUE (STATE_ID);
ALTER TABLE REF_STATE ADD UNIQUE (STATE_NAME);


CREATE TABLE REF_REGION (
    REGION_ID smallint NOT NULL,
    REGION_NAME varchar(64) NOT NULL,
    REF_STATE_ID smallint NOT NULL,
    PRIMARY KEY (REGION_ID)
);
ALTER TABLE REF_REGION ADD UNIQUE (REGION_ID);
ALTER TABLE REF_REGION ADD UNIQUE (REGION_NAME);
ALTER TABLE REF_REGION ADD CONSTRAINT FK_REF_STATE_ID
FOREIGN KEY (REF_STATE_ID) REFERENCES REF_STATE (STATE_ID);


CREATE TABLE REF_DIVISION (
    DIVISION_ID smallint NOT NULL,
    DIVISION_CODE varchar(8) NOT NULL,
    DESCRIPTION varchar(256) NULL,
    PRIMARY KEY (DIVISION_ID)
);
ALTER TABLE REF_DIVISION ADD UNIQUE (DIVISION_ID);
ALTER TABLE REF_DIVISION ADD UNIQUE (DIVISION_CODE);


CREATE TABLE BRANCH (
    BRANCH_ID integer NOT NULL,
    BRANCH_CODE varchar(8) NOT NULL,
    DESCRIPTION varchar(32) NOT NULL,
    ADDRESS varchar(128) NOT NULL,
    REF_REGION_ID smallint NOT NULL,
    PHONE_NUMBER varchar(16) NOT NULL,
    EMAIL_ID varchar(32) NULL,
    MAP_URL varchar(512) NULL DEFAULT NULL,
    PRIMARY KEY (BRANCH_ID)
);
ALTER TABLE BRANCH ADD UNIQUE (BRANCH_ID);
ALTER TABLE BRANCH ADD UNIQUE (BRANCH_CODE);
ALTER TABLE BRANCH ADD CONSTRAINT FK_REF_REGION_ID FOREIGN KEY (REF_REGION_ID) REFERENCES REF_REGION (REGION_ID);
