CREATE TABLE REF_DESIGNATION (
    DESIGNATION_ID integer NOT NULL,
    DESIGNATION varchar(64) NOT NULL,
    PRIMARY KEY (DESIGNATION_ID)
);
ALTER TABLE REF_DESIGNATION ADD UNIQUE (DESIGNATION_ID);
ALTER TABLE REF_DESIGNATION ADD UNIQUE (DESIGNATION);


CREATE TABLE EMPLOYMENT_STATUS (
    STATUS_ID integer NOT NULL,
    DESCRIPTION varchar(64) NOT NULL,
    PRIMARY KEY (STATUS_ID)
);
ALTER TABLE EMPLOYMENT_STATUS ADD UNIQUE (STATUS_ID);
ALTER TABLE EMPLOYMENT_STATUS ADD UNIQUE (DESCRIPTION);


CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID integer NOT NULL,
    EMPLOYEE_NUMBER varchar(10) NOT NULL,
    FIRST_NAME varchar(16) NOT NULL,
    MIDDLE_NAME varchar(16) NOT NULL,
    LAST_NAME varchar(16) NOT NULL,
    GENDER char(1) NOT NULL,
    DATE_OF_BIRTH date NOT NULL,
    BLOOD_GROUP varchar(8) NULL,
    NATIONALITY varchar(8) NULL,
    MARITAL_STATUS varchar(16) NOT NULL,
    WEDDING_DAY date NULL,
    EMPLOYED_AT integer NOT NULL,
    DESIGNATION_ID integer NOT NULL,
    EMPLOYMENT_STATUS_ID integer NOT NULL,
    EMPLOYMENT_START_DATE date NOT NULL,
    EMPLOYMENT_END_DATE date NULL,
    REPORTING_TO integer NULL,
    REMARKS varchar(512) NULL,
    VERIFIED char(1) NOT NULL DEFAULT 'N',
    PRIMARY KEY (EMPLOYEE_ID)
);
ALTER TABLE EMPLOYEE ADD UNIQUE (EMPLOYEE_ID);
ALTER TABLE EMPLOYEE ADD UNIQUE (EMPLOYEE_NUMBER);
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYED_AT FOREIGN KEY (EMPLOYED_AT) REFERENCES BRANCH (BRANCH_ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_DESIGNATION_ID FOREIGN KEY (DESIGNATION_ID) REFERENCES REF_DESIGNATION (DESIGNATION_ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_EMPLOYMENT_STATUS_ID FOREIGN KEY (EMPLOYMENT_STATUS_ID) REFERENCES EMPLOYMENT_STATUS (STATUS_ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_REPORTING_TO FOREIGN KEY (REPORTING_TO) REFERENCES EMPLOYEE (EMPLOYEE_ID);


CREATE TABLE EMPLOYEE_CONTACT (
    EMPLOYEE_ID integer NOT NULL,
    PERMANENT_ADDRESS varchar(512) NULL,
    PRESENT_ADDRESS varchar(512) NOT NULL,
    PERSONAL_MOBILE_NUMBER varchar(16) NOT NULL,
    PERSONAL_EMAIL_ID varchar(32) NULL,
    EMERGENCY_CONTACT_NUMBER varchar(16) NOT NULL,
    EMERGENCY_CONTACT_RELATIONSHIP varchar(10) NOT NULL,
    OFFICE_DESK_PHONE_NUMBER varchar(16) NULL,
    OFFICE_DESK_EXTENSION varchar(10) NULL,
    OFFICE_MOBILE_NUMBER varchar(16) NULL,
    EMAIL_NOTIFICATION_TO char(1) NULL,
    SMS_NOTIFICATION_TO char(1) NULL,
    OFFICE_EMAIL_ID varchar(32) NULL,
    PRIMARY KEY (EMPLOYEE_ID)
);
ALTER TABLE EMPLOYEE_CONTACT ADD UNIQUE (EMPLOYEE_ID);
ALTER TABLE EMPLOYEE_CONTACT ADD CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);
ALTER TABLE EMPLOYEE_CONTACT ADD CONSTRAINT FK_EMERGENCY_CONTACT_RELATIONSHIP FOREIGN KEY (EMERGENCY_CONTACT_RELATIONSHIP) REFERENCES REF_RELATIONSHIP (CODE);


CREATE TABLE EMPLOYEE_DOCUMENT (
    EMPLOYEE_DOCUMENT_ID bigint NOT NULL,
    EMPLOYEE_ID integer NOT NULL,
    DOCUMENT_ID integer NOT NULL,
    DOCUMENT_NUMBER varchar(32) NOT NULL,
    DOCUMENT_EXPIRY_DATE date NULL,
    ISSUED_BY varchar(80) NOT NULL,
    PRIMARY KEY (EMPLOYEE_DOCUMENT_ID)
);
ALTER TABLE EMPLOYEE_DOCUMENT ADD UNIQUE (EMPLOYEE_DOCUMENT_ID);
ALTER TABLE EMPLOYEE_DOCUMENT ADD CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);
ALTER TABLE EMPLOYEE_DOCUMENT ADD CONSTRAINT FK_DOCUMENT_ID FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT (DOCUMENT_ID);


CREATE TABLE EMPLOYEE_EDUCATION (
    EDUCATION_ID bigint NOT NULL,
    EMPLOYEE_ID integer NOT NULL,
    DEGREE varchar(32) NOT NULL,
    SPECIALIZATION varchar(32) NULL,
    YEAR_OF_GRADUATION integer NOT NULL,
    PERCENTAGE integer NOT NULL,
    COLLEGE varchar(64) NOT NULL,
    UNIVERSITY varchar(64) NOT NULL,
    PRIMARY KEY (EDUCATION_ID)
);
ALTER TABLE EMPLOYEE_EDUCATION ADD UNIQUE (EDUCATION_ID);
ALTER TABLE EMPLOYEE_EDUCATION ADD CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);


CREATE TABLE EMPLOYEE_EXPERIENCE (
    EXPERIENCE_ID bigint NOT NULL,
    EMPLOYEE_ID integer NOT NULL,
    EMPLOYER varchar(64) NOT NULL,
    JOB_TITLE varchar(64) NOT NULL,
    FROM_DATE date NOT NULL,
    TO_DATE date NOT NULL,
    EXPERIENCE_IN_MONTHS integer NOT NULL,
    PRIMARY KEY (EXPERIENCE_ID)
);
ALTER TABLE EMPLOYEE_EXPERIENCE ADD UNIQUE (EXPERIENCE_ID);
ALTER TABLE EMPLOYEE_EXPERIENCE ADD CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);


CREATE TABLE EMPLOYEE_PROMOTION (
    PROMOTION_ID bigint NOT NULL,
    EMPLOYEE_ID integer NOT NULL,
    PRIOR_DESIGNATION integer NOT NULL,
    CURRENT_DESIGNATION integer NOT NULL,
    EFFECTIVE_FROM date NOT NULL,
    PRIMARY KEY (PROMOTION_ID)
);
ALTER TABLE EMPLOYEE_PROMOTION ADD UNIQUE (PROMOTION_ID);
ALTER TABLE EMPLOYEE_PROMOTION ADD CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);


CREATE TABLE EMPLOYEE_SUBJECT (
    EMPLOYEE_SUBJECT_ID bigint NOT NULL,
    EMPLOYEE_ID integer NOT NULL,
    SUBJECT_ID integer NOT NULL,
    PRIMARY KEY (EMPLOYEE_SUBJECT_ID)
);
ALTER TABLE EMPLOYEE_SUBJECT ADD UNIQUE (EMPLOYEE_SUBJECT_ID);
ALTER TABLE EMPLOYEE_SUBJECT ADD UNIQUE (EMPLOYEE_ID, SUBJECT_ID);
ALTER TABLE EMPLOYEE_SUBJECT ADD CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);
ALTER TABLE EMPLOYEE_SUBJECT ADD CONSTRAINT FK_SUBJECT_ID FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT (SUBJECT_ID);
ALTER TABLE EMPLOYEE_SUBJECT ADD CONSTRAINT CK_EMPLOYEE_ID_SUBJECT_ID UNIQUE (EMPLOYEE_ID, SUBJECT_ID);
