CREATE TABLE REF_EXAM_GRADE (
    EXAM_GRADE_ID smallint NOT NULL,
    GRADE_NAME varchar(2) NOT NULL,
    PERCENTAGE smallint NOT NULL,
    PRIMARY KEY (EXAM_GRADE_ID)
);
ALTER TABLE REF_EXAM_GRADE ADD UNIQUE (EXAM_GRADE_ID);
ALTER TABLE REF_EXAM_GRADE ADD CONSTRAINT CK_EXAM_GRADE UNIQUE (GRADE_NAME, PERCENTAGE);


CREATE TABLE EXAM (
    EXAM_ID bigint NOT NULL,
    CLASS_ID integer NOT NULL,
    EXAM_NAME varchar(64) NOT NULL,
    EXAM_DATE date NOT NULL,
    EXAM_COMPLETED char(1) NULL DEFAULT 'N',
    PRIMARY KEY (EXAM_ID)
);
ALTER TABLE EXAM ADD UNIQUE (EXAM_ID);
ALTER TABLE EXAM ADD CONSTRAINT FK_CLASS_ID FOREIGN KEY (CLASS_ID) REFERENCES CLASS (CLASS_ID);


CREATE TABLE SUBJECT_EXAM (
    SUBJECT_EXAM_ID bigint NOT NULL,
    EXAM_ID bigint NOT NULL,
    SUBJECT_ID integer NOT NULL,
    MAXIMUM_MARKS smallint NOT NULL,
    PRIMARY KEY (SUBJECT_EXAM_ID)
);
ALTER TABLE SUBJECT_EXAM ADD UNIQUE (SUBJECT_EXAM_ID);
ALTER TABLE SUBJECT_EXAM ADD CONSTRAINT FK_EXAM_ID FOREIGN KEY (EXAM_ID) REFERENCES EXAM (EXAM_ID);
ALTER TABLE SUBJECT_EXAM ADD CONSTRAINT FK_SUBJECT_ID FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECT (SUBJECT_ID);


CREATE TABLE STUDENT_EXAM (
    STUDENT_EXAM_ID bigint NOT NULL,
    STUDENT_ID bigint NOT NULL,
    SUBJECT_EXAM_ID bigint NOT NULL,
    OBTAINED_MARKS smallint NULL,
    PRIMARY KEY (STUDENT_EXAM_ID)
);
ALTER TABLE STUDENT_EXAM ADD UNIQUE (STUDENT_EXAM_ID);
ALTER TABLE STUDENT_EXAM ADD CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID);
ALTER TABLE STUDENT_EXAM ADD CONSTRAINT FK_SUBJECT_EXAM_ID FOREIGN KEY (SUBJECT_EXAM_ID) REFERENCES SUBJECT_EXAM (SUBJECT_EXAM_ID);
ALTER TABLE STUDENT_EXAM ADD CONSTRAINT CK_STUDENT_ID_SUBJECT_EXAM_ID UNIQUE (STUDENT_ID, SUBJECT_EXAM_ID);
