CREATE TABLE ISSUE_STATUS (
    STATUS_ID smallint NOT NULL,
    DESCRIPTION varchar(256) NOT NULL,
    PRIMARY KEY (STATUS_ID)
);

ALTER TABLE ISSUE_STATUS ADD UNIQUE (STATUS_ID);
ALTER TABLE ISSUE_STATUS ADD UNIQUE (DESCRIPTION);


CREATE TABLE ISSUE (
    ISSUE_ID bigint NOT NULL,
    USER_TYPE_ID smallint NOT NULL,
    ISSUE_STATUS_ID int NOT NULL,
    ISSUE_SUBJECT varchar(128) NOT NULL,
    DESCRIPTION varchar(1024) NOT NULL,
    CONTACT_EMAIL_ID varchar(32) NULL,
    REPORTED_DATE date NOT NULL,
    CLOSED_DATE date NULL,
    PRIMARY KEY (ISSUE_ID)
);

ALTER TABLE ISSUE ADD UNIQUE (ISSUE_ID);
ALTER TABLE ISSUE ADD CONSTRAINT FK_ISSUE_STATUS_ID FOREIGN KEY (ISSUE_STATUS_ID) REFERENCES ISSUE_STATUS (STATUS_ID);
ALTER TABLE ISSUE ADD CONSTRAINT FK_USER_TYPE_ID FOREIGN KEY (USER_TYPE_ID) REFERENCES REF_USER_TYPE (USER_TYPE_ID);


CREATE TABLE UPLOAD_STATUS (
    UPLOAD_STATUS_ID int NOT NULL,
    DESCRIPTION varchar(128) NOT NULL,
    PRIMARY KEY (UPLOAD_STATUS_ID)
);
ALTER TABLE UPLOAD_STATUS ADD UNIQUE (UPLOAD_STATUS_ID);


CREATE TABLE UPLOAD_TRACKER (
    TRACKER_ID bigint NOT NULL,
    UPLOAD_STATUS_ID int NOT NULL,
    UPLOAD_TIMESTAMP timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PROCESSED_FILES int NOT NULL DEFAULT 0,
    TOTAL_FILES int NOT NULL DEFAULT 0,
    UPLOADED_BY int NOT NULL,
    PRIMARY KEY (TRACKER_ID)
);
ALTER TABLE UPLOAD_TRACKER ADD UNIQUE (TRACKER_ID);
ALTER TABLE UPLOAD_TRACKER ADD CONSTRAINT FK_UPLOAD_STATUS_ID FOREIGN KEY (UPLOAD_STATUS_ID) REFERENCES UPLOAD_STATUS (UPLOAD_STATUS_ID);
ALTER TABLE UPLOAD_TRACKER ADD CONSTRAINT FK_UPLOADED_BY FOREIGN KEY (UPLOADED_BY) REFERENCES USERS (USER_ID);


CREATE TABLE UPLOAD_FILE_TRACKER (
    UPLOAD_FILE_ID bigint NOT NULL,
    TRACKER_ID bigint NOT NULL,
    UPLOAD_TYPE varchar(128) NOT NULL,
    FILE_NAME varchar(128) NOT NULL,
    UPLOAD_STATUS_ID int NOT NULL,
    UPLOAD_START_TIMESTAMP timestamp NULL DEFAULT NULL,
    UPLOAD_END_TIMESTAMP timestamp NULL DEFAULT NULL,
    PROCESSED_RECORDS int NOT NULL DEFAULT 0,
    TOTAL_RECORDS int NOT NULL DEFAULT 0,
    REMARKS varchar(1024) NULL,
    PRIMARY KEY (UPLOAD_FILE_ID)
);
ALTER TABLE UPLOAD_FILE_TRACKER ADD UNIQUE (UPLOAD_FILE_ID);
ALTER TABLE UPLOAD_FILE_TRACKER ADD CONSTRAINT FK_TRACKER_ID FOREIGN KEY (TRACKER_ID) REFERENCES UPLOAD_TRACKER (TRACKER_ID);
ALTER TABLE UPLOAD_FILE_TRACKER ADD CONSTRAINT FK_UPLOAD_STATUS_ID FOREIGN KEY (UPLOAD_STATUS_ID) REFERENCES UPLOAD_STATUS (UPLOAD_STATUS_ID);


CREATE TABLE UPLOAD_RECORD_TRACKER (
    UPLOAD_RECORD_ID bigint NOT NULL,
    UPLOAD_FILE_ID bigint NOT NULL,
    RECORD_NUMBER bigint NOT NULL,
    RECORD_DATA varchar(1024) NOT NULL,
    UPLOAD_STATUS_ID int NOT NULL,
    REMARKS varchar(1024) NULL,
    PRIMARY KEY (UPLOAD_RECORD_ID)
);
ALTER TABLE UPLOAD_RECORD_TRACKER ADD UNIQUE (UPLOAD_RECORD_ID);
ALTER TABLE UPLOAD_RECORD_TRACKER ADD CONSTRAINT FK_UPLOAD_FILE_ID FOREIGN KEY (UPLOAD_FILE_ID) REFERENCES UPLOAD_FILE_TRACKER (UPLOAD_FILE_ID);
ALTER TABLE UPLOAD_RECORD_TRACKER ADD CONSTRAINT FK_UPLOAD_STATUS_ID FOREIGN KEY (UPLOAD_STATUS_ID) REFERENCES UPLOAD_STATUS (UPLOAD_STATUS_ID);
