-- NOTIFICATION Module
CREATE TABLE NOTIFICATION_END_POINT (
    END_POINT_ID int NOT NULL,
    END_POINT_NAME varchar(16) NOT NULL,
    PRIMARY KEY (END_POINT_ID)
);
ALTER TABLE NOTIFICATION_END_POINT ADD UNIQUE (END_POINT_ID);
ALTER TABLE NOTIFICATION_END_POINT ADD UNIQUE (END_POINT_NAME);


CREATE TABLE NOTIFICATION_MODE (
    MODE_ID int NOT NULL,
    MODE_NAME varchar(16) NOT NULL,
    PRIMARY KEY (MODE_ID)
);
ALTER TABLE NOTIFICATION_MODE ADD UNIQUE (MODE_ID);
ALTER TABLE NOTIFICATION_MODE ADD UNIQUE (MODE_NAME);


CREATE TABLE NOTIFICATION_TYPE (
    TYPE_ID int NOT NULL,
    TYPE_NAME varchar(64) NOT NULL,
    PRIMARY KEY (TYPE_ID)
);
ALTER TABLE NOTIFICATION_TYPE ADD UNIQUE (TYPE_ID);
ALTER TABLE NOTIFICATION_TYPE ADD UNIQUE (TYPE_NAME);


CREATE TABLE NOTIFICATION_TEMPLATE (
    TEMPLATE_ID int NOT NULL,
    END_POINT_ID int NOT NULL,
    MODE_ID int NOT NULL,
    TYPE_ID int NOT NULL,
    PRIMARY KEY (TEMPLATE_ID)
);
ALTER TABLE NOTIFICATION_TEMPLATE ADD UNIQUE (TEMPLATE_ID);
ALTER TABLE NOTIFICATION_TEMPLATE ADD UNIQUE (END_POINT_ID, MODE_ID, TYPE_ID);
ALTER TABLE NOTIFICATION_TEMPLATE ADD CONSTRAINT FK_END_POINT_ID FOREIGN KEY (END_POINT_ID) REFERENCES NOTIFICATION_END_POINT (END_POINT_ID);
ALTER TABLE NOTIFICATION_TEMPLATE ADD CONSTRAINT FK_MODE_ID FOREIGN KEY (MODE_ID) REFERENCES NOTIFICATION_MODE (MODE_ID);
ALTER TABLE NOTIFICATION_TEMPLATE ADD CONSTRAINT FK_TYPE_ID FOREIGN KEY (TYPE_ID) REFERENCES NOTIFICATION_TYPE (TYPE_ID);


CREATE TABLE NOTIFICATION_STATUS (
    STATUS_CODE varchar(16) NOT NULL,
    DESCRIPTION varchar(256) NOT NULL,
    PRIMARY KEY (STATUS_CODE)
);
ALTER TABLE NOTIFICATION_STATUS ADD UNIQUE (STATUS_CODE);


CREATE TABLE NOTIFICATION_HEADER (
    HEADER_ID bigint NOT NULL,
    END_POINT_ID int NOT NULL,
    MODE_ID int NOT NULL,
    TYPE_ID int NOT NULL,
    STATUS_CODE varchar(16) NOT NULL,
    REQUESTED_USER_ID int NOT NULL,
    REQUESTED_DATE date NOT NULL,
    PROCESSED_DATE date NULL,
    COMPLETED_DATE date NULL,
    LAST_UPDATED_USER_ID int NULL,
    PRIMARY KEY (HEADER_ID)
);
ALTER TABLE NOTIFICATION_HEADER ADD UNIQUE (HEADER_ID);
ALTER TABLE NOTIFICATION_HEADER ADD CONSTRAINT FK_STATUS_CODE FOREIGN KEY (STATUS_CODE) REFERENCES NOTIFICATION_STATUS (STATUS_CODE);


CREATE TABLE NOTIFICATION_DETAIL (
    DETAIL_ID bigint NOT NULL,
    HEADER_ID bigint NOT NULL,
    SEND_TO_ID int NOT NULL,
    STATUS_CODE varchar(16) NOT NULL,
    COMPLETED_DATE date NULL,
    LAST_UPDATED_USER_ID int NULL,
    PRIMARY KEY (DETAIL_ID)
);

ALTER TABLE NOTIFICATION_DETAIL ADD UNIQUE (DETAIL_ID);
ALTER TABLE NOTIFICATION_DETAIL ADD CONSTRAINT FK_HEADER_ID FOREIGN KEY (HEADER_ID) REFERENCES NOTIFICATION_HEADER (HEADER_ID);
ALTER TABLE NOTIFICATION_DETAIL ADD CONSTRAINT FK_STATUS_CODE FOREIGN KEY (STATUS_CODE) REFERENCES NOTIFICATION_STATUS (STATUS_CODE);
