CREATE TABLE REF_USER_TYPE (
    USER_TYPE_ID smallint NOT NULL,
    DESCRIPTION varchar(16) NOT NULL,
    PRIMARY KEY (USER_TYPE_ID)
);
ALTER TABLE REF_USER_TYPE ADD UNIQUE (USER_TYPE_ID);
ALTER TABLE REF_USER_TYPE ADD UNIQUE (DESCRIPTION);


CREATE TABLE USERS (
    USER_ID bigint NOT NULL,
    USER_NAME varchar(32) NOT NULL,
    PASSWORD varchar(128) NOT NULL,
    REF_USER_TYPE_ID smallint NOT NULL,
    REF_USER_ID integer NOT NULL,
    PRIMARY KEY (USER_ID)
);
ALTER TABLE USERS ADD UNIQUE (USER_ID);
ALTER TABLE USERS ADD UNIQUE (USER_NAME);
ALTER TABLE USERS
    ADD CONSTRAINT FK_REF_USER_TYPE_ID
    FOREIGN KEY (REF_USER_TYPE_ID)
    REFERENCES REF_USER_TYPE (USER_TYPE_ID);
ALTER TABLE USERS ADD UNIQUE (REF_USER_TYPE_ID, REF_USER_ID);


CREATE TABLE USER_THEME (
    CODE varchar(64) NOT NULL,
    NAME varchar(64) NOT NULL,
    PRIMARY KEY (CODE)
);
ALTER TABLE USER_THEME ADD UNIQUE (CODE);
ALTER TABLE USER_THEME ADD UNIQUE (NAME);


CREATE TABLE USER_PREFERENCES (
    USER_ID bigint NOT NULL,
    THEME_NAME varchar(32) NULL,
    RECORDS_PER_PAGE int NOT NULL DEFAULT 10,
    ALLOW_ADS char(1) NOT NULL DEFAULT 'Y',
    PRIMARY KEY (USER_ID)
);
ALTER TABLE USER_PREFERENCES ADD UNIQUE (USER_ID);
ALTER TABLE USER_PREFERENCES ADD CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);


CREATE TABLE DEFAULT_USER_ACCESS (
    REF_USER_TYPE_ID smallint NOT NULL,
    FUNCTION_ID bigint NOT NULL,
    CAN_VIEW char(1) DEFAULT 'N',
    CAN_CREATE char(1) DEFAULT 'N',
    CAN_UPDATE char(1) DEFAULT 'N',
    CAN_DELETE char(1) DEFAULT 'N',
    PRIMARY KEY (REF_USER_TYPE_ID, FUNCTION_ID)
);
ALTER TABLE DEFAULT_USER_ACCESS ADD CONSTRAINT CK_DEFAULT_USER_FUNCTION UNIQUE (REF_USER_TYPE_ID, FUNCTION_ID);
ALTER TABLE DEFAULT_USER_ACCESS ADD CONSTRAINT FK_FUNCTION_ID FOREIGN KEY (FUNCTION_ID) REFERENCES FUNCTION (FUNCTION_ID);
ALTER TABLE DEFAULT_USER_ACCESS ADD CONSTRAINT FK_REF_USER_TYPE_ID FOREIGN KEY (REF_USER_TYPE_ID) REFERENCES REF_USER_TYPE (USER_TYPE_ID);


CREATE TABLE USER_ACCESS (
    USER_ID bigint NOT NULL,
    FUNCTION_ID bigint NOT NULL,
    CAN_VIEW char(1) DEFAULT 'N',
    CAN_CREATE char(1) DEFAULT 'N',
    CAN_UPDATE char(1) DEFAULT 'N',
    CAN_DELETE char(1) DEFAULT 'N'
);
ALTER TABLE USER_ACCESS ADD CONSTRAINT CK_USER_FUNCTION UNIQUE (USER_ID, FUNCTION_ID);


CREATE TABLE USER_SESSION (
	SESSION_ID varchar(64),
    USER_ID bigint NULL,
    SESSION_START_TIME timestamp NOT NULL default current_timestamp,
    SESSION_END_TIME timestamp NULL,
    DEVICE varchar(64) NOT NULL,
    BROWSER varchar(128) NOT NULL,
    IP_ADDRESS varchar(15) NOT NULL,
    PRIMARY KEY (SESSION_ID)
);
ALTER TABLE  USER_SESSION ADD CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

CREATE TABLE USER_ACTIVITY (
	REQUEST_ID bigint NOT NULL,
	SESSION_ID varchar(64) NOT NULL,
    REQUEST_URL varchar(256) NOT NULL,
    REQUEST_TIME timestamp NOT NULL default current_timestamp,
    SERVED_TIME int NOT NULL,
    PRIMARY KEY (REQUEST_ID)
);
ALTER TABLE USER_ACTIVITY ADD CONSTRAINT FK_SESSION_ID FOREIGN KEY (SESSION_ID) REFERENCES USAGE_STATISTICS (SESSION_ID);
