CREATE TABLE wavefire.STUDENT_APAR_TRANSACTION (
    TRANSACTION_ID bigint NOT NULL,
    ACADEMIC_YEAR varchar(16) NOT NULL,
    STUDENT_ID integer NOT NULL,
    TRANSACTION_NAME varchar(32) NOT NULL,
    DESCRIPTION varchar(128) NULL,
    DUE_DATE date NULL,
    CREDIT_TYPE char(1) NOT NULL,
    AMOUNT double precision NOT NULL,
    TRANSACTION_DATE date NOT NULL,
    PRIMARY KEY (TRANSACTION_ID)
);
ALTER TABLE wavefire.STUDENT_APAR_TRANSACTION ADD UNIQUE (TRANSACTION_ID);
ALTER TABLE wavefire.STUDENT_APAR_TRANSACTION ADD CONSTRAINT FK_ACADEMIC_YEAR FOREIGN KEY (ACADEMIC_YEAR) REFERENCES wavefire.ACADEMICS (ACADEMIC_YEAR_NAME);
ALTER TABLE wavefire.STUDENT_APAR_TRANSACTION ADD CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES wavefire.STUDENT (STUDENT_ID);
ALTER TABLE wavefire.STUDENT_APAR_TRANSACTION ADD CONSTRAINT FK_CREDIT_TYPE FOREIGN KEY (CREDIT_TYPE) REFERENCES wavefire.REF_CREDIT_TYPE (CODE);
