CREATE TABLE wavefire.ORGANIZATION_PROFILE (
    ORGANIZATION_NAME varchar(24) NOT NULL,
    CURRENT_AY_NAME varchar(16) NOT NULL,
    ADDRESS varchar(128) NOT NULL,
    PHONE_NUMBER varchar(16) NOT NULL,
    FAX_NUMBER varchar(16) NULL,
    MAP_URL varchar(512) NULL DEFAULT NULL,
    PRIMARY KEY (ORGANIZATION_NAME)
);
ALTER TABLE wavefire.ORGANIZATION_PROFILE ADD UNIQUE (ORGANIZATION_NAME);
ALTER TABLE wavefire.ORGANIZATION_PROFILE ADD CONSTRAINT FK_ACADEMICS FOREIGN KEY (CURRENT_AY_NAME) REFERENCES wavefire.ACADEMICS (ACADEMIC_YEAR_NAME);


CREATE TABLE wavefire.MYSCHOOL_PROFILE (
    EMAIL_ACTIVE char(1) NOT NULL DEFAULT 'N',
    EMAIL_EMPLOYEES char(1) NOT NULL DEFAULT 'N',
    EMAIL_STUDENTS char(1) NOT NULL DEFAULT 'N',
    SMS_ACTIVE char(1) NOT NULL DEFAULT 'N',
    SMS_EMPLOYEES char(1) NOT NULL DEFAULT 'N',
    SMS_STUDENTS char(1) NOT NULL DEFAULT 'N',
    USE_MENU_ICONS char(1) NOT NULL DEFAULT 'N',
    AYE_IN_PROGRESS char(1) NOT NULL DEFAULT 'N'
);


CREATE TABLE wavefire.REF_RELATIONSHIP (
    CODE char(1) NOT NULL,
    NAME varchar(32) NOT NULL,
    PRIMARY KEY (CODE)
);
ALTER TABLE wavefire.REF_RELATIONSHIP ADD UNIQUE (CODE);
ALTER TABLE wavefire.REF_RELATIONSHIP ADD UNIQUE (NAME);


CREATE TABLE wavefire.REF_CREDIT_TYPE (
    CODE char(1) NOT NULL,
    DESCRIPTION varchar(32) NOT NULL,
    PRIMARY KEY (CODE)
);
ALTER TABLE wavefire.REF_CREDIT_TYPE ADD UNIQUE (CODE);
ALTER TABLE wavefire.REF_CREDIT_TYPE ADD UNIQUE (DESCRIPTION);

CREATE TABLE wavefire.DOCUMENT (
    DOCUMENT_ID integer NOT NULL,
    DOCUMENT_NAME varchar(64) NOT NULL,
    DESCRIPTION varchar(512) NOT NULL,
    STUDENT_APPLICABLE char(1) NOT NULL DEFAULT 'N',
    EMPLOYEE_APPLICABLE char(1) NOT NULL DEFAULT 'N',
    PRIMARY KEY (DOCUMENT_ID)
);
ALTER TABLE wavefire.DOCUMENT ADD UNIQUE (DOCUMENT_ID);
ALTER TABLE wavefire.DOCUMENT ADD UNIQUE (DOCUMENT_NAME);


CREATE TABLE wavefire.REF_MODULE (
    MODULE_ID smallint NOT NULL,
    MODULE_NAME varchar(32) NOT NULL,
    CAN_ADMIN_ACCESS varchar(1) NOT NULL,
    CAN_EMPLOYEE_ACCESS varchar(1) NOT NULL,
    CAN_STUDENT_ACCESS varchar(1) NOT NULL,
    ACCESS_URL varchar(64) NULL,
    PRIMARY KEY (MODULE_ID)
);

ALTER TABLE wavefire.REF_MODULE ADD UNIQUE (MODULE_ID);
ALTER TABLE wavefire.REF_MODULE ADD UNIQUE (MODULE_NAME);


CREATE TABLE wavefire.FUNCTION (
    FUNCTION_ID bigint NOT NULL,
    FUNCTION_NAME varchar(32) NOT NULL,
    REF_MODULE_ID smallint NOT NULL,
    ACCESS_URL varchar(64) NULL,
    ICON_URL varchar(64) NULL,
    PRIMARY KEY (FUNCTION_ID)
);
ALTER TABLE wavefire.FUNCTION ADD UNIQUE (FUNCTION_ID);
ALTER TABLE wavefire.FUNCTION ADD CONSTRAINT FK_REF_MODULE_ID FOREIGN KEY (REF_MODULE_ID) REFERENCES wavefire.REF_MODULE (MODULE_ID);
