CREATE TABLE wavefire.REF_REGION (
    REGION_ID smallint NOT NULL,
    REGION_NAME varchar(64) NOT NULL,
    PRIMARY KEY (REGION_ID)
);
ALTER TABLE wavefire.REF_REGION ADD UNIQUE (REGION_ID);
ALTER TABLE wavefire.REF_REGION ADD UNIQUE (REGION_NAME);


CREATE TABLE wavefire.REF_DIVISION (
    DIVISION_ID smallint NOT NULL,
    DIVISION_CODE varchar(8) NOT NULL,
    DESCRIPTION varchar(256) NULL,
    PRIMARY KEY (DIVISION_ID)
);
ALTER TABLE wavefire.REF_DIVISION ADD UNIQUE (DIVISION_ID);
ALTER TABLE wavefire.REF_DIVISION ADD UNIQUE (DIVISION_CODE);


CREATE TABLE wavefire.BRANCH (
    BRANCH_ID integer NOT NULL,
    BRANCH_CODE varchar(8) NOT NULL,
    DESCRIPTION varchar(32) NOT NULL,
    ADDRESS varchar(128) NOT NULL,
    REF_REGION_ID smallint NOT NULL,
    PHONE_NUMBER varchar(16) NOT NULL,
    EMAIL_ID varchar(32) NULL,
    MAP_URL varchar(512) NULL DEFAULT NULL,
    PRIMARY KEY (BRANCH_ID)
);
ALTER TABLE wavefire.BRANCH ADD UNIQUE (BRANCH_ID);
ALTER TABLE wavefire.BRANCH ADD UNIQUE (BRANCH_CODE);
ALTER TABLE wavefire.BRANCH ADD CONSTRAINT FK_REF_REGION_ID FOREIGN KEY (REF_REGION_ID) REFERENCES wavefire.REF_REGION (REGION_ID);
