-- Token Module
CREATE TABLE wavefire.TOKEN (
    TOKEN_ID varchar(128) NOT NULL,
    CONSUMED_BY varchar(128) NOT NULL,
    NECESSITY varchar(128) NOT NULL,
    GENERATED_ON date NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DISPOSED_ON date NULL,
    VALIDITY int NULL,
    PRIMARY KEY (TOKEN_ID)
);
ALTER TABLE wavefire.TOKEN_ID ADD UNIQUE (TOKEN_ID);
