INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('BRANCH_REPORT', 'Branch Report', 'Y', 'Y', 'N');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('DESIGNATION_REPORT', 'Designation Report', 'Y', 'Y', 'N');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('DIVISION_REPORT', 'Division Report', 'Y', 'Y', 'N');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('MASTER_DOCUMENT_REPORT', 'Master Document Report', 'Y', 'Y', 'N');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('EMPLOYEE_REPORT', 'Employee Report', 'Y', 'Y', 'N');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('EXAM_GRADE_REPORT', 'Exam Grade Report', 'Y', 'Y', 'Y');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('HOLIDAY_REPORT', 'Holiday Report', 'Y', 'Y', 'Y');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('MASTER_CLASS_REPORT', 'Master Class Report', 'Y', 'Y', 'N');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('RELATIONSHIP_CODE_REPORT', 'Relationship Code Report', 'Y', 'Y', 'N');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('SCHOOL_REPORT', 'School Report', 'Y', 'Y', 'N');
INSERT INTO REPORT (REPORT_KEY, REPORT_NAME, CAN_ADMIN_VIEW, CAN_EMPLOYEE_VIEW, CAN_STUDENT_VIEW) VALUES ('STUDENT_REPORT', 'Student Report', 'Y', 'Y', 'Y');

-- Report Criteria data load
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('BRANCH_REPORT', 'Region', 'SELECTION', 'REGION', 'VALUE');

INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Blood Group', 'SELECTION', 'BLOOD_GROUP', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Date Of Birth', 'DATE_RANGE', NULL,  NULL);
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Designation', 'SELECTION', 'DESIGNATION', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Employed At', 'SELECTION', 'BRANCH', 'VALUE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Employee Name', 'TEXT', NULL, NULL);
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Employee Number', 'TEXT', NULL, NULL);
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Employment Date', 'DATE_RANGE', NULL,  NULL);
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Employment Status', 'SELECTION', 'EMPLOYMENT_STATUS',  'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Experience', 'TEXT_RANGE', NULL, NULL);
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Gender', 'SELECTION', 'GENDER', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Reporting To', 'SELECTION', 'REPORTING_TO', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('EMPLOYEE_REPORT', 'Verified Status', 'SELECTION', 'VERIFIED_STATUS', 'CODE');

INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('HOLIDAY_REPORT', 'Academic Year', 'SELECTION', 'ACADEMIC_YEAR', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('HOLIDAY_REPORT', 'Date Between', 'DATE_RANGE', NULL, NULL);

INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('MASTER_DOCUMENT_REPORT', 'Applicable For', 'SELECTION', 'DOCUMENT_APPLICABLE_FOR', 'VALUE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('MASTER_DOCUMENT_REPORT', 'Document Applicability', 'SELECTION', 'DOCUMENT_APPLICABILITY', 'CODE');

INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('SCHOOL_REPORT', 'Branch', 'SELECTION', 'BRANCH', 'VALUE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('SCHOOL_REPORT', 'Division', 'SELECTION', 'DIVISION', 'CODE');

INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Admission Number', 'TEXT', NULL, NULL);
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Blood Group', 'SELECTION', 'BLOOD_GROUP', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Gender', 'SELECTION', 'GENDER', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Religion', 'SELECTION', 'RELIGION', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Branch', 'SELECTION', 'BRANCH', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Division', 'SELECTION', 'DIVISION', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'School', 'SELECTION', 'SCHOOL', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Class', 'SELECTION', 'CLASS', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Medium', 'SELECTION', 'MEDIUM', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Section', 'SELECTION', 'SECTION', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Verified Status', 'SELECTION', 'VERIFIED_STATUS', 'CODE');
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Student Name', 'TEXT', NULL, NULL);
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Date Of Birth', 'DATE_RANGE', NULL,  NULL);
INSERT INTO REPORT_CRITERIA (REPORT_KEY, CRITERIA_NAME, CONTROL_TYPE, REFERENCE, USE) VALUES ('STUDENT_REPORT', 'Date Of Joining', 'DATE_RANGE', NULL,  NULL);
